LetItGo.watch_frozen(File, :absolute_path,     positions: [0])
LetItGo.watch_frozen(File, :atime,     positions: [0])
LetItGo.watch_frozen(File, :birthtime,     positions: [0])
LetItGo.watch_frozen(File, :blockdev?,     positions: [0])
LetItGo.watch_frozen(File, :chardev?,     positions: [0])
LetItGo.watch_frozen(File, :file_name,     positions: [0])
LetItGo.watch_frozen(File, :directory?,     positions: [0])
LetItGo.watch_frozen(File, :dirname,     positions: [0])
LetItGo.watch_frozen(File, :executable?,     positions: [0])
LetItGo.watch_frozen(File, :exist?,     positions: [0])
LetItGo.watch_frozen(File, :exists?,     positions: [0])
LetItGo.watch_frozen(File, :extname,     positions: [0])
LetItGo.watch_frozen(File, :file?,     positions: [0])
LetItGo.watch_frozen(File, :ftype,     positions: [0])
LetItGo.watch_frozen(File, :mtime,     positions: [0])
LetItGo.watch_frozen(File, :owned?,     positions: [0])
LetItGo.watch_frozen(File, :path,     positions: [0])
LetItGo.watch_frozen(File, :readable?,     positions: [0])
LetItGo.watch_frozen(File, :rename,     positions: [0])
LetItGo.watch_frozen(File, :size,     positions: [0])
LetItGo.watch_frozen(File, :socket?,     positions: [0])
LetItGo.watch_frozen(File, :split,     positions: [0])
LetItGo.watch_frozen(File, :stat,     positions: [0])
LetItGo.watch_frozen(File, :truncate,     positions: [0])
LetItGo.watch_frozen(File, :utime,     positions: [0])
LetItGo.watch_frozen(File, :zero?,     positions: [0])


LetItGo.watch_frozen(File, :basename,     positions: [0, 1])
LetItGo.watch_frozen(File, :expand_path,     positions: [0, 1])
LetItGo.watch_frozen(File, :identical?,     positions: [0, 1])
LetItGo.watch_frozen(File, :new,     positions: [0, 1])
LetItGo.watch_frozen(File, :open,     positions: [0, 1])

LetItGo.watch_frozen(File, :fnmatch?,     positions: [0, 1, 2])
LetItGo.watch_frozen(File, :join,     positions: [0, 1, 2])
